### ISSUE TITLE
分开导入缺少NetworkAPI+Rx.swift 以及NetworkAPIOO+Rx.swift文件

### ISSUE THREAD

**Issue by SnailLoveSmile** [yangKJ/RxNetworks#15]
当我分开进行导入的时候:
pod 'RxNetworks/MoyaNetwork'
pod 'RxNetworks/HandyJSON'
pod 'RxNetworks/MoyaPlugins/Cache'

这时候MoyaNetwork文件夹下缺少NetworkAPI+Rx.swift 以及NetworkAPIOO+Rx.swift 不能进行request()的操作

xcode 14.3  pod --version 1.12.1

还有就是我用您的工程 进行pod install lottie-ios 会缺少 AnimationView 这个文件有LottieAnimationView 文件
报错了工程
 谢谢

**Comment by yangKJ** [comment]
NetworkAPI+Rx.swift 以及NetworkAPIOO+Rx.swift是属于RxSwift模块，
AnimationView是属于lottie-ios这个仓库的文件，我测试过没问题。
你在看看！
