### ISSUE TITLE
pods  #  use_frameworks!   use_modular_headers! 

### ISSUE THREAD

**Issue by sclt-k** [yangKJ/RxNetworks#16]
<unknown>:0: error: cannot load underlying module for 'Alamofire'  是不支持静态库下依赖吗，还是需要配置其他？

**Comment by yangKJ** [comment]
这个库是基于moya的基础上二次封装使用

**Comment by sclt-k** [comment]
直接使用moya+Alamofire 静态库可以，pod RxNetworks不行
