### ISSUE TITLE
pod 导入后报错

### ISSUE THREAD

**Issue by coderDeviCheng** [yangKJ/RxNetworks#17]
<img width="911" alt="image" src="https://github.com/yangKJ/RxNetworks/assets/34669007/9c5d99cd-112c-432d-8d68-89f643c5e14f">
<img width="275" alt="image" src="https://github.com/yangKJ/RxNetworks/assets/34669007/46da856a-dea9-4499-a6f8-9f675cd148bc">

**Comment by yangKJ** [comment]
已更新兼容最新版本Lottie
