### ISSUE TITLE
最新版的AuthPlugin  lastNever 方法中tuple.result 不存在了的

### ISSUE THREAD

**Issue by SnailLoveSmile** [yangKJ/RxNetworks#20]
<img width="733" alt="截屏2024-01-16 11 14 38" src="https://github.com/yangKJ/RxNetworks/assets/33648940/7c863111-8b30-40d7-8be4-1b48d555f5b0">

**Comment by SnailLoveSmile** [comment]
<img width="822" alt="截屏2024-01-16 13 29 54" src="https://github.com/yangKJ/RxNetworks/assets/33648940/0b68785f-b0bf-4959-bd1b-6f218ac1c2fd">
今天更新后发现之前的版本只需在.failure 判断401 现在.success 中也要判断401了.

**Comment by cdoky** [comment]
先用着，今天晚点我换一个优化版本

**Comment by SnailLoveSmile** [comment]
收到
