### ISSUE TITLE
导入新版，编译报错

### ISSUE THREAD

**Issue by coderWeil** [yangKJ/RxNetworks#25]
![截屏2024-07-04 10 06 17](https://github.com/yangKJ/RxNetworks/assets/14228146/063e6d3f-c78d-4448-b31e-dd78b889e7a1)

**Comment by coderWeil** [comment]
导入方式是直接 pod 'Booming'  pod 'RxNetworks/Swift'

**Comment by yangKJ** [comment]
RxNetworks/RxSwift模块不在维护，请自行根据项目二次封装
Demo有提供参考用例
