### ISSUE TITLE
更新后少了UITextField的分类

### ISSUE THREAD

**Issue by Link-Start** [yangKJ/RxNetworks#3]
老哥，更新之后UITextField的分类不见了诶

**Comment by yangKJ** [comment]
我之前重新整理了一下，有点混乱然后就按模块拆解出去了。
这边我也写了详细的Swift使用Demo，供参考：https://github.com/yangKJ/KJCategories
你重新导入新库，pod 'KJCategories'
pod 'KJCategories/UIKit'
pod 'KJCategories/Foundation'
pod 'KJCategories/Opencv'
