### ISSUE TITLE
刷新token

### ISSUE THREAD

**Issue by nobut** [yangKJ/RxNetworks#6]
有刷新token的插件、或者实现方式嘛

**Comment by yangKJ** [comment]
这个肯定是有的瑟，只是每个人的网络处理情况都不一样的，
所以这边是没法封装成通用插件供你们使用，
可以简单提供一点思路去封装。
其实核心就是简单的去拦截返回结果，然后解析在Moya的`prepare`注入即可。
这块网上应该也有蛮多关于Moya刷新token的封装Demo

**Comment by nobut** [comment]
请问刷新数据怎么处理呀、比如分页或者和mj刷新绑定

**Comment by yangKJ** [comment]
你可以参考一下我的另外一个仓库，
[Rickenbacker](https://github.com/yangKJ/Rickenbacker)
这里面我有写的有关于刷新分页的处理。

**Comment by cdoky** [comment]
项目中加入了一个AuthPlugin, 可以参考一下
[AuthPlugin.swift](https://github.com/yangKJ/RxNetworks/blob/master/RxNetworks/Modules/Auth/AuthPlugin.swift)

**Comment by nobut** [comment]
<img width="854" alt="Screen Shot 2022-08-20 at 08 36 56" src="https://user-images.githubusercontent.com/28843198/185722508-ef919099-8b44-4ea8-a816-e597c51fbdf4.png">
pod update 没有这个方法
在我项目是这个
    func lastNever(_ tuple: LastNeverTuple, target: TargetType) -> LastNeverTuple {
        return tuple
    }

**Comment by cdoky** [comment]
建议你先跑demo看看，
毕竟这个改动比较大，怕影响到其他用户
