### ISSUE TITLE
上传文件

### ISSUE THREAD

**Issue by wish-pig** [yangKJ/RxNetworks#7]
能上传文件吗，有上传文件的实例吗？

**Comment by yangKJ** [comment]
肯定可以瑟，其实我这边只是简单的再Moya的基础上增加协议，
核心还是原先moya那一套，原先Moya和Alamofire可以实现的功能依然可以实现的哈～

**Comment by wish-pig** [comment]
没事，其实我本想问的是可以对上传文件进行封装下吗？我看你封装了压缩，所有想着图片也可以走压缩->上传文件这样的流程呢，有默认的插件就好了 哈哈

**Comment by yangKJ** [comment]
已新增支持上传和下载文件资源插件`NetworkFilesPlugin`
