### ISSUE TITLE
MVVM的使用如果获取请求失败

### ISSUE THREAD

**Issue by fengshuo1992** [yangKJ/RxNetworks#9]
比如现在我HomeAPI.recommend("1004587")
			.request()
			.mapHandyJSON(HandyDataModel<[HomeRoomInfoModel]>.self)
			.compactMap({$0.data}).observe(on: MainScheduler.instance)
			.catchAndReturn([])
比如我的View 中有下拉刷新 我在请求接口的时候  如果请求失败了 我要通知到view中停止headerView的刷新  这种情况要怎么搞

**Comment by yangKJ** [comment]
简单的处理就是你.catchAndReturn([])这句不要，在订阅的地方去处理你的失败即可
